### ISSUE TITLE
Crash while playing with Lord of the Rings Mod

### ISSUE THREAD

**Issue by KuroNeko87** [OreCruncher/Restructured#3]
Hello! I've been playing with this mod for a while with no issues but I decided to explore the middle earth dimension and got a nasty crash!

https://gist.githubusercontent.com/KuroNeko87/c4621f341840daea719c/raw/bbd6219a3ca8d07ea705f709859b9033d9e653bf/forgelog.txt

A sample of the long log
[15:27:53] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.ChunkWatchEvent$UnWatch@6ea6bc2f:
java.lang.NullPointerException
    at org.blockartistry.mod.Restructured.assets.Assets.getTableForWorldGen(Assets.java:390) ~[Assets.class:?]
    at org.blockartistry.mod.Restructured.world.SchematicWorldGenHandler.generate(SchematicWorldGenHandler.java:147) ~[SchematicWorldGenHandler.class:?]

**Comment by OreCruncher** [comment]
Can you link the restructured.cfg and the schematics.cfg file?

EDIT:  Also there were changes in the v1.0.1.2 version of the mod in this particular area.  I recommend updating to the latest and see if the issue persists. http://minecraft.curseforge.com/mc-mods/230570-restructured/files

**Comment by KuroNeko87** [comment]
https://gist.github.com/KuroNeko87/3beeb06a477451380298

I didn't know there was a new version, will try and let you know

**Comment by KuroNeko87** [comment]
2 hrs ago, no wonder! ;p

**Comment by KuroNeko87** [comment]
Same deal.

I'll just Blacklist that dimension. I think it is because LOTR mod handles biomes differently

**Comment by OreCruncher** [comment]
Ok.  Sent a PM to the person who keeps the www.minecraftforum.net LOTR page asking for a dev version of the mod.  The public BETA does not play well within a development environment.

**Comment by OreCruncher** [comment]
To date haven't received a response.  Will pursue different avenues/

**Comment by OreCruncher** [comment]
@KuroNeko87 Still unable to obtain the information I need related to this report.  However, the underlying mechanisms in Restructured change with v1.0.3.x and it would be worthy to try the latest release with LOTR to see if the problem goes away.
