### ISSUE TITLE
[1.1.0.0ALPHA] Error with the world sometimes...

### ISSUE THREAD

**Issue by hvdklauw** [OreCruncher/Restructured#5]
I can usually create a world just fine.. when suddenly I get the following error:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  thaumicinfusion (ThaumicInfusion-Hotifx-1.8.9-4.72.jar)
  FMLPlugin (InventoryTweaks-1.60-dev-28.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 13-1-16 13:33
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access method net.minecraft.entity.EntityHanging.func_174859_a(Lnet/minecraft/util/EnumFacing;)V from class org.blockartistry.mod.Restructured.component.CopyStructureBuilder
    at org.blockartistry.mod.Restructured.component.CopyStructureBuilder.generate(CopyStructureBuilder.java:162)
    at org.blockartistry.mod.Restructured.component.SchematicStructure.build(SchematicStructure.java:109)
    at org.blockartistry.mod.Restructured.component.VillageStructureBase.func_74875_a(VillageStructureBase.java:96)
    at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:46)
    at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:86)
    at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_73153_a(ChunkProviderGenerateBOP.java:491)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:261)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1081)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:307)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:109)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:123)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 187351968 bytes (178 MB) / 1101004800 bytes (1050 MB) up to 5368709120 bytes (5120 MB)
    JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m -XX:+UseG1GC
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 105
    FML: MCP 9.19 Powered by Forge 11.15.0.1694 35 mods loaded, 35 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1694.jar) 
    UCHIJAA Forge{11.15.0.1694} [Minecraft Forge] (forge-1.8.9-11.15.0.1694.jar) 
    UCHIJAA ActuallyAdditions{1.8.9-r23} [Actually Additions] (ActuallyAdditions-1.8.9-r23.jar) 
    UCHIJAA bagginses{@VERSION@} [Bagginses] (Bagginses-2.1.3-1.8.9.jar) 
    UCHIJAA BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1624-universal.jar) 
    UCHIJAA BloodMagic{1.8.9-2.0.0-4} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-4.jar) 
    UCHIJAA chiselsandbits{@version@} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8-beta8.jar) 
    UCHIJAA clayworldgen{v1.0.0} [Clay WorldGen] (ClayWorldGen-1.0.1.jar) 
    UCHIJAA craftingtweaks{3.0.15} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.15.jar) 
    UCHIJAA DurabilityShow{2.1.2} [Durability Show] (Durability Show-1.8.9-2.1.2.jar) 
    UCHIJAA ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.2.jar) 
    UCHIJAA flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.5.jar) 
    UCHIJAA inventorytweaks{1.60-dev-28-3253249} [Inventory Tweaks] (InventoryTweaks-1.60-dev-28.jar) 
    UCHIJAA JEI{2.16.2.78} [Just Enough Items] (jei_1.8.9-2.16.2.78.jar) 
    UCHIJAA Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAA Thaumcraft{5.1.3} [Thaumcraft] (Thaumcraft-1.8.9-5.1.3.jar) 
    UCHIJAA JEIAddons{0.8.1.30} [Just Enough Items Addons] (JEIAddons_1.8.9-0.8.1.30.jar) 
    UCHIJAA journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAA jeresources{0.0.3.@BUILD@} [Just Enough Resources] (JustEnoughResources-1.8.9-0.0.3.jar) 
    UCHIJAA testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAA MultiPageChest{1.4.0} [Multi Page Chest] (MultiPageChest-1.4.0-MC1.8.9.jar) 
    UCHIJAA notenoughwands{1.2.4} [Not Enough Wands] (notenoughwands-1.8.9-1.2.4.jar) 
    UCHIJAA packingtape{0.3} [Packing Tape] (Packing Tape-0.3.jar) 
    UCHIJAA PneumaticCraft{1.13.0 - err} [PneumaticCraft] (PneumaticCraft-1.8.8-1.13.1-universal.jar) 
    UCHIJAA progressiveautomation{1.6.16} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.16.jar) 
    UCHIJAA restructured{1.1.0.0ALPHA} [Restructured] (Restructured-1.8.9-1.1.0.0ALPHA.jar) 
    UCHIJAA rftools{4.20beta8} [RFTools] (rftools-1.8.9-4.20beta8.jar) 
    UCHIJAA Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAA thaumicinfusion{4.72} [Thaumic Infusion] (ThaumicInfusion-Hotifx-1.8.9-4.72.jar) 
    UCHIJAA totemic{1.8.9-0.6.4.1} [Totemic] (Totemic-1.8.9-0.6.4.1.jar) 
    UCHIJAA VeinMiner{0.31.2_build.unknown} [Vein Miner] (VeinMiner-1.8.9_0.31.2.unknown.jar) 
    UCHIJAA VeinMinerModSupport{0.31.2_build.unknown} [Mod Support] (VeinMiner-1.8.9_0.31.2.unknown.jar) 
    UCHIJAA Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAA wawla{1.4.1} [What Are We Looking At] (Wawla-1.4.1-1.8+.jar) 
    Loaded coremods (and transformers): 
thaumicinfusion (ThaumicInfusion-Hotifx-1.8.9-4.72.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
FMLPlugin (InventoryTweaks-1.60-dev-28.jar)
  invtweaks.forge.asm.ContainerTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)

    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by OreCruncher** [comment]
Looks like the AT transformer didn't fire.  Have you used Forge versions other than 1694?  Also, can you post a pastebin link to the entire client log?  There may be things in there that can give me clues.

EDIT:  Also try Forge 1696.  There is a change entry related to runtime transformations which could affect this.

**Comment by hvdklauw** [comment]
I'll give it a try with 1695 (can't download 1696 through curse somehow)

The log was too big for pastebin, so used an alternative.

https://paste.ee/p/mlda9

**Comment by OreCruncher** [comment]
Thanks!  Looked like Forge loaded the transformer rules but didn't apply them, or for some reason the rule didn't match.  Let me know how it goes with 1696.  Until then I will keep looking.

**Comment by OreCruncher** [comment]
Found the issue.  Was a bad transform.  Posting an update to CurseForge and it will be available once they approve it.  http://minecraft.curseforge.com/projects/restructured/files

**Comment by hvdklauw** [comment]
Awesome, thanks !
